# Generated by Django 3.0.4 on 2021-03-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0118_emailrecord'),
        ('frontendv2', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recv_messages_old', to='corm.Member'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages_old', to=settings.AUTH_USER_MODEL),
        ),
    ]
