# Generated by Django 3.1.2 on 2021-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendv2', '0005_publicdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicdashboard',
            name='display_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
