# Generated by Django 3.1.2 on 2022-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendv2', '0007_auto_20210916_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerinvite',
            name='role',
        ),
        migrations.AlterField(
            model_name='publicdashboard',
            name='page',
            field=models.CharField(choices=[('overview', 'Overview'), ('members', 'Members'), ('conversations', 'Conversations'), ('contributions', 'Contributions'), ('contributors', 'Contributors'), ('report', 'Report')], max_length=32),
        ),
    ]
