# Generated by Django 3.0.4 on 2020-03-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0003_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='channel',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='corm.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, to='corm.Member'),
        ),
    ]
