# Generated by Django 3.0.4 on 2020-03-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0007_auto_20200305_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='community',
        ),
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(to='corm.Member'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(choices=[('corm.plugins.email', 'Email'), ('corm.plugins.slack', 'Slack')], max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('icon_name', models.CharField(max_length=256)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Source'),
        ),
    ]
