# Generated by Django 3.0.4 on 2020-03-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0008_auto_20200319_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='icon_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
