# Generated by Django 3.0.4 on 2020-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0011_auto_20200319_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='server',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.email', 'Email'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discourse', 'Discourse')], max_length=256),
        ),
    ]
