# Generated by Django 3.0.4 on 2020-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0015_auto_20200319_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.email', 'Email'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.reddit', 'Reddit')], max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(),
        ),
    ]
