# Generated by Django 3.0.4 on 2020-03-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0021_auto_20200324_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community'),
        ),
    ]
