# Generated by Django 3.0.4 on 2020-03-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0022_auto_20200324_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='corm.Member')),
                ('via', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Source')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='connections',
            field=models.ManyToManyField(through='corm.MemberConnection', to='corm.Member'),
        ),
    ]
