# Generated by Django 3.0.4 on 2020-03-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0024_auto_20200324_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Conversation'),
        ),
    ]
