# Generated by Django 3.0.4 on 2020-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0025_task_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('timestamp',), 'verbose_name_plural': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('detail',)},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('done', 'due')},
        ),
        migrations.AddField(
            model_name='member',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='memberconnection',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
