# Generated by Django 3.0.4 on 2020-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0028_remove_member_origin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
