# Generated by Django 3.0.4 on 2020-03-26 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0029_auto_20200326_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('community', 'user')},
        ),
    ]
