# Generated by Django 3.0.4 on 2020-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0030_auto_20200326_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberconnection',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='community',
            name='icon_path',
            field=models.CharField(default='/static/savannah/Savannah32.png', max_length=256),
            preserve_default=False,
        ),
    ]
