# Generated by Django 3.0.4 on 2020-04-10 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0031_auto_20200410_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberconnection',
            options={'ordering': ('-last_connected',)},
        ),
        migrations.RenameField(
            model_name='memberconnection',
            old_name='timestamp',
            new_name='first_connected',
        ),
        migrations.AddField(
            model_name='member',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberconnection',
            name='last_connected',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
