# Generated by Django 3.0.4 on 2020-04-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0032_auto_20200410_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberconnection',
            options={'ordering': ('-first_connected',)},
        ),
        migrations.AddField(
            model_name='source',
            name='last_import',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
