# Generated by Django 3.0.4 on 2020-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0035_auto_20200416_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated list of words. If found in a conversation, this tag will be applied.', max_length=256, null=True),
        ),
    ]
