# Generated by Django 3.0.4 on 2020-04-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0038_auto_20200422_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Channel'),
        ),
        migrations.AddField(
            model_name='activity',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_in', to='corm.Member'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='thread_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.Conversation'),
        ),
    ]
