# Generated by Django 3.0.4 on 2020-04-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('corm', '0039_auto_20200423_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityType',
            new_name='ContributionType',
        ),
        migrations.RenameModel(
            old_name='Activity',
            new_name='Contribution',
        ),
        migrations.RenameField(
            model_name="contribution",
            old_name="activity_type",
            new_name="contribution_type"
        ),
        migrations.AlterModelOptions(
            name='contributiontype',
            options={'verbose_name': 'Contribution Type', 'verbose_name_plural': 'Contribution Types'},
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
    ]
