# Generated by Django 3.0.4 on 2020-04-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0041_auto_20200424_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Tag'),
        ),
    ]
