# Generated by Django 3.0.4 on 2020-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0044_auto_20200428_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
