# Generated by Django 3.0.4 on 2020-05-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0045_auto_20200428_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.email', 'Email'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.github', 'Github'), ('corm.plugins.twitter', 'Twitter'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack')], max_length=256),
        ),
        migrations.CreateModel(
            name='SuggestMemberTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Accepted'), (0, 'Ignored'), (-1, 'Rejected')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('suggested_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_suggestions', to='corm.Tag')),
                ('target_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to='corm.MemberConnection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestMemberMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Accepted'), (0, 'Ignored'), (-1, 'Rejected')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('destination_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_with_suggestions', to='corm.MemberConnection')),
                ('source_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_to_suggestions', to='corm.MemberConnection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggesConversationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Accepted'), (0, 'Ignored'), (-1, 'Rejected')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('suggested_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_suggestions', to='corm.Tag')),
                ('target_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to='corm.Conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
