# Generated by Django 3.0.4 on 2020-05-05 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0046_auto_20200505_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuggesConversationTag',
            new_name='SuggestConversationTag',
        ),
    ]
