# Generated by Django 3.0.4 on 2020-05-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0047_auto_20200505_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestmembermerge',
            name='destination_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_with_suggestions', to='corm.Member'),
        ),
        migrations.AlterField(
            model_name='suggestmembermerge',
            name='source_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_to_suggestions', to='corm.Member'),
        ),
    ]
