# Generated by Django 3.0.4 on 2020-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0049_auto_20200512_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='origin_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
