# Generated by Django 3.0.4 on 2020-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0050_auto_20200512_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date_added',
            new_name='first_seen',
        ),
        migrations.AddField(
            model_name='member',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
