# Generated by Django 3.0.4 on 2020-05-16 16:25

from django.db import migrations
from django.db.models import Min, Max

def set_first_last_seen(apps, schema_editor):
    Conversation = apps.get_model('corm', 'Conversation')
    Member = apps.get_model('corm', 'Member')
    members = Member.objects.all().annotate(first_convo=Min('conversation__timestamp'), last_convo=Max('conversation__timestamp'))
    for member in members:
        needs_saving = False
        if member.first_convo is not None and (member.first_seen is None or member.first_seen > member.first_convo):
            member.first_seen = member.first_convo
            needs_saving = True
        if member.last_convo is not None and (member.last_seen is None or member.last_seen < member.last_convo):
            member.last_seen = member.last_convo
            needs_saving = True
        if needs_saving:
            member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0051_auto_20200516_1605'),
    ]

    operations = [
        migrations.RunPython(set_first_last_seen)
    ]

