# Generated by Django 3.0.4 on 2020-05-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0052_auto_20200516_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='location',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
