# Generated by Django 3.0.4 on 2020-05-25 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0053_auto_20200516_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.twitter', 'Twitter'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.github', 'Github'), ('corm.plugins.rss', 'RSS')], max_length=256)),
                ('server', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_id', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
