# Generated by Django 3.0.4 on 2020-05-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0054_userauthcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('community', 'Community'), ('staff', 'Staff'), ('bot', 'Bot')], default='community', max_length=32),
        ),
    ]
