# Generated by Django 3.0.4 on 2020-05-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0055_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
