# Generated by Django 3.0.4 on 2020-06-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0056_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(null=True, upload_to='community_logos'),
        ),
    ]
