# Generated by Django 3.0.4 on 2020-07-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0059_auto_20200611_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('location', models.URLField(blank=True, max_length=512, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Channel')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Conversation')),
                ('promoters', models.ManyToManyField(to='corm.Member')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Source')),
                ('tags', models.ManyToManyField(blank=True, to='corm.Tag')),
            ],
            options={
                'verbose_name_plural': 'Promotions',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField()),
                ('location', models.URLField(blank=True, max_length=512, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Channel')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('promotions', models.ManyToManyField(to='corm.Promotion')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Source')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Tag')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ('start_timestamp',),
            },
        ),
    ]
