# Generated by Django 3.0.4 on 2020-06-26 13:57

from django.db import migrations

def set_project_owners(apps, schema_editor):
    Community = apps.get_model('corm', 'Community')
    Project = apps.get_model('corm', 'Project')
    for c in Community.objects.all():
        created = Project.objects.get_or_create(community=c, name=c.name, owner=None)

    MemberLevel = apps.get_model('corm', 'MemberLevel')
    for p in Project.objects.all():
        if p.collaborators.all().count() > 0:
            p.owner = p.collaborators.all()[0]
            p.save()

        for c in p.collaborators.all():
            MemberLevel.objects.get_or_create(community=p.community, project=p, member=c, level=2)

def unset_project_owners(apps, schema_editor):
    Project = apps.get_model('corm', 'Project')
    MemberLevel = apps.get_model('corm', 'MemberLevel')
    for p in Project.objects.all():
        for c in MemberLevel.objects.filter(project=p):
            p.collaborators.add(c.member)

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0060_auto_20200626_1356'),
    ]

    operations = [
        migrations.RunPython(set_project_owners, unset_project_owners)
    ]
