# Generated by Django 3.0.4 on 2020-06-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0061_auto_20200626_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='collaborators',
        ),
    ]
