# Generated by Django 3.0.4 on 2020-06-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0062_remove_project_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlevel',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Consumer'), (1, 'Casual'), (2, 'Contributor'), (3, 'Core')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='memberlevel',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='corm.Member'),
        ),
    ]
