# Generated by Django 3.0.4 on 2020-06-26 14:34

from django.db import migrations, models
import django.db.models.deletion

def set_task_project(apps, schema_editor):
    Task = apps.get_model('corm', 'Task')
    Project = apps.get_model('corm', 'Project')
    for t in Task.objects.all():
        if t.project is None:
            t.project = Project.objects.get(community=t.community, name=t.community.name)
            t.save()

def unset_task_project(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0063_auto_20200626_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='channels',
            field=models.ManyToManyField(blank=True, to='corm.Channel'),
        ),
        migrations.RunPython(set_task_project, unset_task_project),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Project'),
        ),
    ]
