# Generated by Django 3.0.4 on 2020-07-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0064_auto_20200626_1434'),
        ('corm', '0060_event_promotion'),
    ]

    operations = [
    ]
