# Generated by Django 3.0.4 on 2020-07-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0066_auto_20200719_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_project',
            field=models.BooleanField(default=False),
        ),
    ]
