# Generated by Django 3.0.4 on 2020-07-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0067_project_default_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='threshold_period',
            field=models.SmallIntegerField(default=365, help_text='Timerange in days to look at for level activity'),
        ),
    ]
