# Generated by Django 3.0.4 on 2020-07-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0068_project_threshold_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlevel',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'Core'), (2, 'Contributor'), (1, 'Participant'), (0, 'User')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='corm.Member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='threshold_participant',
            field=models.SmallIntegerField(default=3, help_text='Conversations to become a Participant'),
        ),
    ]
