# Generated by Django 3.0.4 on 2020-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0069_auto_20200720_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='threshold_contributor',
            field=models.SmallIntegerField(default=1, help_text='Number of contributions needed to become a Contributor', verbose_name='Contributor level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='threshold_core',
            field=models.SmallIntegerField(default=5, help_text='Number of contributions needed to become a Core Contributor', verbose_name='Core level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='threshold_participant',
            field=models.SmallIntegerField(default=3, help_text='Number of conversations needed to become a Participant', verbose_name='Participant level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='threshold_period',
            field=models.SmallIntegerField(default=365, help_text='Timerange in days to look at for level activity', verbose_name='Activity Period'),
        ),
        migrations.AlterField(
            model_name='project',
            name='threshold_user',
            field=models.SmallIntegerField(default=1, help_text='Number of conversations needed to become a User', verbose_name='User level'),
        ),
    ]
