# Generated by Django 3.0.4 on 2020-07-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0070_auto_20200726_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contents', models.TextField()),
                ('discontinued', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('sent_date', models.DateTimeField()),
                ('received_date', models.DateTimeField()),
                ('tracking', models.CharField(blank=True, max_length=512, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('gift_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.GiftType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Member')),
            ],
            options={
                'ordering': ('-sent_date',),
            },
        ),
    ]
