# Generated by Django 3.0.4 on 2020-07-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0071_gift_gifttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
