# Generated by Django 3.0.4 on 2020-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0072_auto_20200727_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gifttype',
            options={'ordering': ('discontinued', 'name')},
        ),
        migrations.AlterField(
            model_name='gift',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
