# Generated by Django 3.0.4 on 2020-07-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0073_auto_20200727_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Community Name'),
        ),
        migrations.AlterField(
            model_name='memberlevel',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'Core'), (2, 'Contributor'), (1, 'Participant'), (0, 'Visitor')], default=0, null=True),
        ),
    ]
