# Generated by Django 3.0.4 on 2020-09-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0080_managerprofile_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='thread_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='corm.Conversation'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Preferred Email'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='realname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Preferred Name'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='send_notifications',
            field=models.BooleanField(default=True, verbose_name='Send emails'),
        ),
    ]
