# Generated by Django 3.0.4 on 2020-10-16 17:27

from django.db import migrations, models

def set_active(apps, schema_editor):
    Community = apps.get_model('corm', 'Community')
    for c in Community.objects.all():
        if c.member_set.all().count() > 0:
            c.status = 1 #Active
            c.save()

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0084_auto_20201010_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Setup'), (1, 'Active'), (2, 'Suspended'), (3, 'Deactive'), (4, 'Archived')], default=0),
        ),
        migrations.RunPython(set_active, noop)
    ]
