# Generated by Django 3.0.4 on 2020-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0085_community_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(help_text='Will be resized to a 32x32px icon.', null=True, upload_to='community_logos', verbose_name='Community Logo'),
        ),
    ]
