# Generated by Django 3.0.4 on 2020-12-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0086_auto_20201026_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberwatch',
            name='last_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Channel'),
        ),
        migrations.AddField(
            model_name='memberwatch',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
