# Generated by Django 3.0.4 on 2020-12-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0087_auto_20201210_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Member', verbose_name='Member Profile'),
        ),
    ]
