# Generated by Django 3.0.4 on 2020-12-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0089_auto_20201228_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS')], max_length=256),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS')], max_length=256),
        ),
    ]
