# Generated by Django 3.0.4 on 2021-01-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0090_auto_20201230_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.SmallIntegerField(choices=[(0, 'Growth'), (1, 'Annual')]),
        ),
    ]
