# Generated by Django 3.0.4 on 2021-01-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0091_auto_20210107_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifttype',
            name='impact',
            field=models.IntegerField(default=0),
        ),
    ]
