# Generated by Django 3.0.4 on 2021-01-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0092_gifttype_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='impact',
            field=models.IntegerField(default=0),
        ),
    ]
