# Generated by Django 3.0.4 on 2021-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0093_gift_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='import_failed_attempts',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='import_failed_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='import_failed_attempts',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='import_failed_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(help_text='Will be resized to a 32x32px icon.', null=True, upload_to='community_logos', verbose_name='Community Icon'),
        ),
    ]
