# Generated by Django 3.0.4 on 2021-01-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0095_auto_20210121_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companydomains',
            options={'ordering': ('domain',), 'verbose_name': 'Company Domain', 'verbose_name_plural': 'Company Domains'},
        ),
        migrations.AddField(
            model_name='company',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.Tag'),
        ),
    ]
