# Generated by Django 3.0.4 on 2021-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0099_channel_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
