# Generated by Django 3.0.4 on 2021-01-27 20:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0100_auto_20210127_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMergeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('merged_date', models.DateField(auto_now_add=True)),
                ('data', jsonfield.fields.JSONField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('merged_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Member')),
            ],
        ),
    ]
