# Generated by Django 3.0.4 on 2021-01-28 00:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0101_membermergerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermergerecord',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
