# Generated by Django 3.0.4 on 2021-01-29 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0102_auto_20210128_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256),
        ),
        migrations.CreateModel(
            name='SuggestCompanyCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Accepted'), (0, 'Ignored'), (-1, 'Rejected')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(max_length=256)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
