# Generated by Django 3.0.4 on 2021-02-11 21:35

from django.db import migrations

def noop(apps, schema_editor):
    pass

def rename_contrib_types(apps, schema_editor):
    ContributionType = apps.get_model('corm', 'ContributionType')
    ContributionType.objects.filter(name='Answer').update(name='Support')

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0104_source_oldest_import'),
    ]

    operations = [
        migrations.RunPython(rename_contrib_types, noop),
    ]
