# Generated by Django 3.0.4 on 2021-02-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0106_auto_20210217_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='conversation',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.Contribution'),
        ),
    ]
