# Generated by Django 3.0.4 on 2021-02-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0107_auto_20210217_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='connector',
            field=models.CharField(blank=True, choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='corm.Contribution'),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256),
        ),
    ]
