# Generated by Django 3.0.4 on 2021-03-08 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid

def noop(apps, schema_editor):
    pass

def backward(apps, schema_editor):
    Conversation = apps.get_model('corm', 'Conversation')
    Participant = apps.get_model('corm', 'Participant')
    for p in Participant.objects.all():
        c = p.conversation
        c.participants.add(p.member)

def forward(apps, schema_editor):
    Conversation = apps.get_model('corm', 'Conversation')
    Participant = apps.get_model('corm', 'Participant')
    for c in Conversation.objects.all():

        for p in c.participants.all():
            Participant.objects.create(community=p.community, conversation=c, member_id=p.id, initiator_id=c.speaker_id, timestamp=c.timestamp)


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0109_auto_20210303_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Conversation')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator_of', to='corm.Member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_in', to='corm.Member')),
            ],
        ),
        migrations.RunPython(forward, backward),

    ]
