# Generated by Django 3.0.4 on 2021-03-12 16:18

from django.db import migrations, models
import django.db.models.deletion

def noop(apps, schema_editor):
    pass

def forward(apps, schema_editor):
    MemberConnection = apps.get_model('corm', 'MemberConnection')
    for c in MemberConnection.objects.all():
        c.community = c.from_member.community
        c.save()

def backwards(apps, schema_editor):
    MemberConnection = apps.get_model('corm', 'MemberConnection')
    for c in MemberConnection.objects.all():
        try:
            c.via = c.community.source_set.all()[0]
            c.save()
        except:
            c.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0111_auto_20210308_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberconnection',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.Community'),
            preserve_default=False,
        ),
        migrations.RunPython(forward, backwards),
        migrations.RemoveField(
            model_name='memberconnection',
            name='via',
        ),
        migrations.AlterField(
            model_name='memberconnection',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community'),
        ),
    ]
