# Generated by Django 3.0.4 on 2021-03-13 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0112_memberconnection_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Accepted'), (0, 'Ignored'), (-1, 'Rejected')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=50)),
                ('score', models.SmallIntegerField(default=0)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
