# Generated by Django 3.0.4 on 2021-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0115_suggesttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='suggest_company',
            field=models.BooleanField(default=True, help_text='Suggest new Companies based on email addresses'),
        ),
        migrations.AddField(
            model_name='community',
            name='suggest_contribution',
            field=models.BooleanField(default=True, help_text='Suggest Contributions based on Conversation text'),
        ),
        migrations.AddField(
            model_name='community',
            name='suggest_merge',
            field=models.BooleanField(default=True, help_text='Suggest merging accounts belonging to the same person'),
        ),
        migrations.AddField(
            model_name='community',
            name='suggest_tag',
            field=models.BooleanField(default=True, help_text='Suggest new Tags based on Conversation text'),
        ),
        migrations.AddField(
            model_name='community',
            name='suggest_task',
            field=models.BooleanField(default=True, help_text='Suggest Tasks to help engage with your Members'),
        ),
    ]
