# Generated by Django 3.0.4 on 2021-03-16 22:25

from django.db import migrations

def noop(apps, schema_editor):
    pass

def forward(apps, schema_editor):
    Conversation = apps.get_model('corm', 'Conversation')
    MemberMergeRecord = apps.get_model('corm', 'MemberMergeRecord')
    for record in MemberMergeRecord.objects.all():
        removed = record.data['removed']
        Conversation.objects.filter(speaker__isnull=True, id__in=removed.get('conversations', [])).update(speaker=record.merged_with)

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0116_auto_20210314_1925'),
    ]

    operations = [
        migrations.RunPython(forward, noop)
    ]
