# Generated by Django 3.0.4 on 2021-04-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0118_emailrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Setup'), (1, 'Active'), (2, 'Suspended'), (3, 'Deactive'), (4, 'Archived'), (5, 'Demonstration')], default=0),
        ),
    ]
