# Generated by Django 3.0.4 on 2021-04-16 16:17

from django.db import migrations, models
import uuid

def noop(apps, schema_editor):
    pass

def set_uuids(apps, schema_editor):
    ManagerProfile = apps.get_model('corm', 'ManagerProfile')
    for p in ManagerProfile.objects.all():
        p.secret_key = uuid.uuid4()
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0119_auto_20210401_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(set_uuids, noop),
    ]
