# Generated by Django 3.0.4 on 2021-04-21 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0120_auto_20210416_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='impact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='impact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange')], max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='connector',
            field=models.CharField(blank=True, choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange')], max_length=256),
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='corm.Member')),
            ],
        ),
    ]
