# Generated by Django 3.0.4 on 2021-04-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0121_auto_20210421_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='corm.Event'),
        ),
    ]
