# Generated by Django 3.0.4 on 2021-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0122_auto_20210422_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('icon_name', models.CharField(blank=True, max_length=256, null=True)),
                ('short_description', models.CharField(max_length=256)),
                ('long_description', models.CharField(max_length=256)),
                ('location', models.URLField(blank=True, max_length=512, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Channel')),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.Contribution')),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.Conversation')),
                ('event_attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.EventAttendee')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='corm.Member')),
                ('tags', models.ManyToManyField(blank=True, to='corm.Tag')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
