# Generated by Django 3.0.14 on 2021-05-27 14:26

from django.db import migrations
from django.db.models import Count, Min

def noop(app, schema_editor):
    pass

def remove_duplicate_participation(apps, schema_editor):
    Participant = apps.get_model('corm', 'Participant')
    for dup in Participant.objects.all().values('member_id', 'conversation_id').annotate(dup_count=Count('id', distinct=True), min_id=Min('id')).filter(dup_count__gt=1):
        Participant.objects.filter(conversation_id=dup['conversation_id'], member_id=dup['member_id']).exclude(id=dup['min_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0125_suggestconversationascontribution_activity'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_participation, noop),
    ]
