# Generated by Django 3.0.14 on 2021-07-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0126_auto_20210527_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='connector',
            field=models.CharField(blank=True, choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce')], max_length=256),
        ),
    ]
