# Generated by Django 3.1.2 on 2021-08-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0127_auto_20210709_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member_tag',
            field=models.ForeignKey(blank=True, help_text="Any activity by a member with this tag will be included in this project's activity", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_by_member', to='corm.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ForeignKey(blank=True, help_text="Content with this tag will be included in this project's activity", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_by_content', to='corm.tag'),
        ),
    ]
