# Generated by Django 3.1.2 on 2021-08-16 21:39

from django.db import migrations, models

def auth_secret_to_api_key(apps, schema_editor):
    Source = apps.get_model('corm', 'Source')
    for api_source in Source.objects.filter(connector="corm.plugins.api"):
        api_source.api_key = api_source.auth_secret
        api_source.auth_secret = None
        api_source.save()

def api_key_to_auth_secret(apps, schema_editor):
    Source = apps.get_model('corm', 'Source')
    for api_source in Source.objects.filter(connector="corm.plugins.api"):
        api_source.auth_secret = api_source.api_key
        api_source.api_key = None
        api_source.save()

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0129_auto_20210806_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='api_key',
            field=models.CharField(max_length=256, blank=True, editable=False, null=True),
        ),
        migrations.RunPython(auth_secret_to_api_key, api_key_to_auth_secret),
    ]
