# Generated by Django 3.1.2 on 2022-01-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0131_auto_20211029_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Event URL'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('speaker', 'Speaker'), ('staff', 'Staff')], default='guest', max_length=32),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.facebook', 'Facebook')], max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='connector',
            field=models.CharField(blank=True, choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.facebook', 'Facebook')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.facebook', 'Facebook')], max_length=256),
        ),
    ]
