# Generated by Django 3.1.2 on 2022-02-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0133_auto_20220131_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('host', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=64, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.community')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='links',
            field=models.ManyToManyField(to='corm.Hyperlink'),
        ),
    ]
