# Generated by Django 3.1.2 on 2022-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0135_auto_20220203_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperlink',
            name='ignored',
            field=models.BooleanField(default=False, help_text='Ignore links that are not interesting to you, or are added automatically to conversations.'),
        ),
    ]
