# Generated by Django 3.1.2 on 2022-03-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0136_hyperlink_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='auto_update_avatar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='auto_update_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='auto_update_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='auto_update_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='auto_update_role',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.facebook', 'Facebook'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.twitter', 'Twitter')], max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='connector',
            field=models.CharField(blank=True, choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.facebook', 'Facebook'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.twitter', 'Twitter')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.facebook', 'Facebook'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.twitter', 'Twitter')], max_length=256),
        ),
    ]
