# Generated by Django 3.1.2 on 2022-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0137_auto_20220302_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, help_text='Will be resized to a 32x32px icon.', null=True, upload_to='community_logos', verbose_name='Community Icon'),
        ),
        migrations.AlterField(
            model_name='member',
            name='auto_update_avatar',
            field=models.BooleanField(default=True, verbose_name='Auto Update Avatar'),
        ),
        migrations.AlterField(
            model_name='member',
            name='auto_update_company',
            field=models.BooleanField(default=True, verbose_name='Auto Update Company'),
        ),
        migrations.AlterField(
            model_name='member',
            name='auto_update_email',
            field=models.BooleanField(default=True, verbose_name='Auto Update Email Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='auto_update_name',
            field=models.BooleanField(default=True, verbose_name='Auto Update Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='auto_update_role',
            field=models.BooleanField(default=True, verbose_name='Auto Update Role'),
        ),
    ]
