# Generated by Django 3.1.2 on 2022-05-16 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0138_auto_20220321_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_timestamp', models.DateTimeField()),
                ('impact_score', models.IntegerField(default=0)),
                ('impact_1d', models.IntegerField(default=0)),
                ('impact_7d', models.IntegerField(default=0)),
                ('impact_15d', models.IntegerField(default=0)),
                ('impact_30d', models.IntegerField(default=0)),
                ('impact_60d', models.IntegerField(default=0)),
                ('impact_90d', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('start_timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20)),
                ('text', models.TextField()),
                ('link', models.URLField()),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('uid', models.CharField(max_length=256)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.community')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
