# Generated by Django 3.1.2 on 2022-05-16 20:56

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0139_impactreport_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.utcnow()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insight',
            name='title',
            field=models.CharField(default='No title', max_length=256),
            preserve_default=False,
        ),
    ]
