# Generated by Django 3.1.2 on 2022-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0140_auto_20220516_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='cta',
            field=models.CharField(blank=True, default='More...', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
