# Generated by Django 3.1.2 on 2022-07-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0142_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.source'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status_msg',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='mapping',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Uploaded'), (1, 'Pending'), (2, 'Processing'), (3, 'Complete'), (4, 'Failed'), (5, 'Canceled')], default=0),
        ),
    ]
