# Generated by Django 3.1.2 on 2022-08-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0144_opportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='opportunities', to='corm.Activity'),
        ),
        migrations.CreateModel(
            name='OpportunityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.SmallIntegerField(choices=[(-2, 'Rejected'), (-1, 'Declined'), (0, 'Identified'), (1, 'Proposed'), (2, 'Agreed'), (3, 'Submitted'), (4, 'Complete')], default=0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.community')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='corm.opportunity')),
            ],
        ),
    ]
