# Generated by Django 3.1.2 on 2022-08-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0145_auto_20220808_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corm.event'),
        ),
    ]
