# Generated by Django 3.1.2 on 2022-09-22 17:51

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0147_uploadedfile_import_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.community'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.source'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.source'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.community'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corm.source'),
        ),

    ]
