# Generated by Django 3.1.2 on 2023-01-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corm', '0150_auto_20220926_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=64, verbose_name='Event')),
                ('target', models.URLField(max_length=255, verbose_name='Target URL')),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Setup'), (1, 'Active'), (2, 'Suspended'), (3, 'Deactive'), (4, 'Archived'), (5, 'Demonstration'), (6, 'Development')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.channel'),
        ),
        migrations.CreateModel(
            name='WebHookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=256)),
                ('payload', models.JSONField()),
                ('success', models.BooleanField(default=False)),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='corm.webhook')),
            ],
        ),
        migrations.AddField(
            model_name='webhook',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.community'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
