# Generated by Django 3.1.2 on 2023-01-07 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0152_webhookeventlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhook',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='webhookeventlog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='webhook',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
