# Generated by Django 3.1.2 on 2023-05-18 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0155_auto_20230427_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='joined_end',
            field=models.DateTimeField(blank=True, help_text="Any activity by a member first seen before this date will have their activity included in this segment's activity", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='joined_start',
            field=models.DateTimeField(blank=True, help_text="Any activity by a member first seen after this date will have their activity included in this segment's activity", null=True),
        ),
        migrations.AlterField(
            model_name='memberlevel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.project', verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='channels',
            field=models.ManyToManyField(blank=True, help_text="Any activity in these channels will be included in this segment's activity", to='corm.Channel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member_tag',
            field=models.ForeignKey(blank=True, help_text="Any activity by a member with this tag will be included in this segment's activity", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_by_member', to='corm.tag', verbose_name='Member tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ForeignKey(blank=True, help_text="Any content with this tag will be included in this segment's activity", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_by_content', to='corm.tag', verbose_name='Content tag'),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.facebook', 'Facebook'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.twitter', 'Twitter'), ('corm.plugins.bluesky', 'Bluesky')], max_length=256),
        ),
        migrations.AlterField(
            model_name='suggesttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_suggestions', to='corm.project', verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='connector',
            field=models.CharField(blank=True, choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.facebook', 'Facebook'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.twitter', 'Twitter'), ('corm.plugins.bluesky', 'Bluesky')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.project', verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='userauthcredentials',
            name='connector',
            field=models.CharField(choices=[('corm.plugins.null', 'Manual Entry'), ('corm.plugins.api', 'API'), ('corm.plugins.discord', 'Discord'), ('corm.plugins.discourse', 'Discourse'), ('corm.plugins.github', 'Github'), ('corm.plugins.gitlab', 'Gitlab'), ('corm.plugins.facebook', 'Facebook'), ('corm.plugins.ical', 'iCal'), ('corm.plugins.meetup', 'Meetup'), ('corm.plugins.reddit', 'Reddit'), ('corm.plugins.rss', 'RSS'), ('corm.plugins.slack', 'Slack'), ('corm.plugins.stackexchange', 'Stack Exchange'), ('corm.plugins.salesforce', 'Salesforce'), ('corm.plugins.twitter', 'Twitter'), ('corm.plugins.bluesky', 'Bluesky')], max_length=256),
        ),
    ]
