# Generated by Django 3.0.4 on 2020-10-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('corm', '0086_auto_20201026_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company/Organization Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email Address')),
                ('communities', models.ManyToManyField(through='billing.Management', to='corm.Community')),
                ('customer', models.ForeignKey(blank=True, help_text="The team's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='management',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Organization'),
        ),
        migrations.AddField(
            model_name='management',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The team's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Subscription'),
        ),
    ]
