# Generated by Django 3.0.4 on 2021-02-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0104_source_oldest_import'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corm.Community'),
        ),
    ]
