# Generated by Django 3.0.4 on 2021-04-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0123_activity'),
        ('billing', '0002_auto_20210203_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_management', to='corm.Community'),
        ),
    ]
