# Generated by Django 3.1.2 on 2021-12-13 16:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210422_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='overrides',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
