# Generated by Django 3.0.14 on 2021-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstration',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
